app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_book_api:
    resource: |
        alias: api.book
    type: sylius.resource_api
    prefix: /api


app_book_html:
   resource: |
       alias: html.book
   type: sylius.resource
   prefix: /html
